---
- name: Copy the systemd service templates
  template: src=instance.service.j2 dest=/home/core/{{ item }}.service
  with_items: instances
  notify: roll update

- name: Copy the sidekick systemd service templates
  template: src=sidekick.service.j2 dest=/home/core/{{ item }}.sidekick.service
  with_items: instances
  notify: roll update
