---
- name: Copy the systemd service templates
  template: src=instance.service.j2 dest=/home/core/{{ item }}.service
  with_items: instances

- name: Copy the sidekick systemd service templates
  template: src=sidekick.service.j2 dest=/home/core/{{ item }}.sidekick.service
  with_items: instances

- name: Submit the instances to fleet
  shell: fleetctl submit /home/core/{{ item }}.service /home/core/{{ item }}.sidekick.service
  with_items: instances

- name: Start the instances on the fleet cluster
  shell: fleetctl start {{ item }}.service {{ item }}.sidekick.service
  with_items: instances
